### ISSUE TITLE
Assertion fail at (_workQueue != NULL)

### ISSUE THREAD

**Issue by Sam-Hoult** [callstack-internal/react-native-socket-mobile#6]
Hey, I'm not sure what is going on with this piece of code but it's stopping me debugging my entire app as this assertion always fails and then seems to spin up more threads? (I'm new to Objective-C so not sure what's going on but I can't debug other areas of the app and the app stops running based on this failure)

Any information on why this is happening and help to either ignore it if it's not an issue or whether it is an app killing issue would be appreciated.

![image](https://user-images.githubusercontent.com/1436841/39716058-1926731e-51e4-11e8-9cd6-7b6631d18c4a.png)

**Comment by Sam-Hoult** [comment]
Sorry for the delayed response and lack of details.

This occurs whilst running the app on a physical iPad, running with the react-native debug configuration. Bluetooth is enabled.

Running on a physical device with: 
iOS -  11.3 (and again on 11.3.1)
React Native - 0.54.2

Reproduction:
This shows up intermittently whilst running from xCode in a debug scheme, running from the packer. Sometimes I can debug for a while and it doesn't show up. Always lots of threads being created, however doesn't always show. 

I've even disabled that assertion, but then the dispatch underneath fails with a `EXC_BAD_ACCESS`. Again, intermittently.

I'll post more details as I find them.

Does the amount of threads make sense though?

**Comment by ujwal-setlur** [comment]
I am running into this issue as well, and I don't use this package, so I think it is a react-native issue...
